export const INQUIRY_OPTIONS = [
  "HOST THE ESCAPING THE ODDS DOCUMENTARY IMPACT SERIES",
  "LICENSE THE BOUNCE FORWARD PLAN CURRICULUM",
  "EXPLORE VOCATIONAL PATHWAYS",
  "INDIVIDUAL LEARNING (BOOKS & COURSES)",
  "MEDIA / PRESS",
  "GENERAL INQUIRY",
];

export const TIMELINE_OPTIONS = [
  "WITHIN 30 DAYS",
  "1–3 MONTHS",
  "3–6 MONTHS",
  "6+ MONTHS",
  "EXPLORING OPTIONS",
];

export const ROLE_OPTIONS = [
  "FINAL DECISION MAKER",
  "KEY INFLUENCER",
  "RESEARCHER / EVALUATOR",
  "OTHER",
];
